apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nc-data
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/nfs_shares/kubernetes/nextcloud/data
    server: 192.168.1.99